services:
  - type: web
    name: money-tracker-db
    env: node
    repo: https://github.com/vigneshvicky123456/Money_Tracker_Pern/tree/main/Backend
    region: Singapore (Southeast Asia)
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: money_tracker_db
          property: connectionString
      - key: PORT
        value: 3003
